ALTER TABLE EGRUL_DEV2.SPVIDLIC MODIFY NAME VARCHAR2(4000);
CREATE TABLE EGRUL_DEV2.VIDLIC
(
  IDLIC    INT NOT NULL,
  IDVIDLIC INT NOT NULL
);
ALTER TABLE EGRUL_DEV2.VIDLIC
ADD FOREIGN KEY (IDLIC) REFERENCES LICENZ (IDLIC);
ALTER TABLE EGRUL_DEV2.VIDLIC
ADD FOREIGN KEY (IDVIDLIC) REFERENCES SPVIDLIC (IDVIDLIC);