# Logging configuration
logging:
    level:
        .: error
        org.springframework: ERROR

# Server configuration
server:
    port: 8080

spring:
    liquibase:
        change-log: classpath:db/changelog/db-changelog-master.xml
        check-change-log-location: true
        enabled: true
    hikari:
        auto-commit: true
        connectionTimeout: 20000
        maximumPoolSize: 5
    jpa:
        open-in-view: false
        database: postgresql
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    profiles:
        active: "test"
    main:
        banner-mode: "off"

app:
    count-files-to-max-threads: 1
    maxthreads: 10
    threads: 1
    tmp-data-dir: c:\tmp\egrulegrip_data\

---
spring:
    profiles: developer
    datasource:
        url: jdbc:postgresql://localhost:5454/egrulegrip_test_spring
        username: EGRUL_DEV2
        password: 123
        driver-class-name: org.postgresql.Driver

---
spring:
    profiles: test
    datasource:
#        url: jdbc:postgresql://10:146:136:40:8200/egrulegrip
        url: jdbc:postgresql://localhost:5454/egrulegrip_test
        username: EGRUL_DEV2
        password: 123


---
spring:
    profiles: predrelease
    datasource:
        url: jdbc:postgresql://host:port/egrulegrip
        username: EGRUL_DEV2
        password: 123

---
spring:
    profiles: production
    datasource:
        url: jdbc:postgresql://host:port/egrulegrip
        username: EGRUL_DEV2
        password: 123

